nb:
  lib_dir: "<?php echo nbConfig::get('nb_bee_dir','.').'/'; ?>lib"
  command_dir: "<?php echo nbConfig::get('nb_bee_dir','.').'/'; ?>lib/command"
  test_dir: test/unit
  project_config: project.yml
  template_dir: "<?php echo nbConfig::get('nb_bee_dir','.').'/'; ?>data/template"
  plugin_dir: "<?php echo nbConfig::get('nb_bee_dir','.').'/'; ?>plugin"
